
def dna_count(dna: str) -> str:
    """[summary]
    
    Arguments:
        dna {str} -- A DNA string s of length at most 1000 nt.
    
    Returns:
        str --  Four integers (separated by spaces) counting
            the respective number of times that the symbols
            'A', 'C', 'G', and 'T' occur in s.
    """

    a = 0
    c = 0
    g = 0
    t = 0
    for char in dna:
        if char == 'A':
            a += 1
        if char == 'C':
            c += 1
        if char == 'G':
            g += 1
        if char == 'T':
            t += 1
    print(f'{a} {c} {g} {t}')

dna_count('CCTTGCTACGCGATATGGACGAACTAATTTTATTTGTCGTGGACTCGTTAAGAAATTCTGCTGTAACCTCTGCTGAACCGACAACTAGCTGCCACACCTCAACAATGTCCTCGCGTTAGTAATCGAATGTGATTACCGACCTCTGCCCGTGAGCACGTTTGCTGAGTAGGCTCTTTAATGAACGTCAACTGCCTTTTCTGGTTCACTAGGCTGCGCCGTTGAAATCTCATTCAACTAAACACACTACGTCAAGGGATTAAGGATACTGTTCTGATAAGGTCTCTTTAAATCAATAGGTGGGTGATGTAATTGGAGCGTAAAAGTAAACAATGCTCATACGTGATCTTCGCCATCAGAAGATGGATCCACCGGGCCTTCTCGTATGTTGACTACTTAATCCCACCCGTGGAATCGCAACAAGGGTCTTCGTGGATGTCACCCTGGAGTGAAAGCATAAGACATGGATATAGATTAGGAGATACGGCTGACATCCAACTCACATGACTGTGACTCGACCGGAGGCAAGACTCAATACTTGGCTTAGGACCTTATTCGACATGAGACCCTTATTTACTATATACTTTCATGTCCCATAGCGCACAGGCCAAGAGGAGAGCTGCCCAGACCACCTGTTTTTTTGACAAGGCACCACAAGTTACAAGCAGCCGGAGATTTCTTGATAATTGATCTCGTGGGAAGGTGGTGCAGAATTTCGGCGGGCAAAATCCTGAGCACCACATAAATGCCGAATTCTTTCCGGCCGCGCCTACGGCCACGGAGCGAATTACTTGTCCAAAGTACACCCTTAATACTGAGGGGATGTACTACCAATTCCCGGGCGTGTGGCCTGACTCCTCCATTTCCGACGACCGGCCGCCAAATGTAAGAAAATACTCGCTAAATTTTGTCGCCCAATCTCATTCGTCGAGGAGCTAGGTGTGAGAATCCTTCGCTTCTGTTTTGAGGGATTC')